version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-prod
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_HOST=${DB_MYSQLDB_HOST:-mysql}
      - DB_MYSQLDB_PORT=${DB_MYSQLDB_PORT:-3306}
      - DB_MYSQLDB_DATABASE=${DB_MYSQLDB_DATABASE:-n8n}
      - DB_MYSQLDB_USER=${DB_MYSQLDB_USER:-n8n}
      - DB_MYSQLDB_PASSWORD=${DB_MYSQLDB_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-https}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_LOG_LEVEL=${N8N_LOG_LEVEL:-info}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_USER_MANAGEMENT_DISABLED=${N8N_USER_MANAGEMENT_DISABLED:-false}
      - N8N_RUNNERS_ENABLED=${N8N_RUNNERS_ENABLED:-true}
    volumes:
      - ./workflows:/home/node/.n8n/workflows
      - ./credentials:/home/node/.n8n/credentials
      - ./data:/home/node/.n8n
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge 